@extends('layouts.admin')
@section('title', 'Manage Hosts')
@section('content')
<div class="admin-page-head"><div><h1>Manage Hosts</h1><p>Assign host access and manage existing hosts.</p></div><span class="admin-badge badge-green">{{ $hosts->total() }} hosts</span></div>
<div class="row g-3">
<div class="col-xl-4"><div class="admin-card"><div class="admin-card-header"><h2>Assign Host Role</h2></div><div class="admin-card-body"><form method="POST" action="{{ $users->count() ? route('admin.hosts.assign',$users->first()->id) : '#' }}" id="assignHostForm">@csrf<div class="mb-3"><label class="admin-form-label">Select user</label><select class="admin-form-control" id="hostUser" required><option value="">Choose a user</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }} — {{ $user->email }}</option>@endforeach</select></div><button class="admin-btn admin-btn-primary w-100" type="submit" {{ $users->isEmpty() ? 'disabled' : '' }}><i class="ti ti-user-plus"></i> Make Host</button></form></div></div></div>
<div class="col-xl-8"><div class="admin-card"><div class="admin-card-header"><h2>Current Hosts</h2></div><div class="table-responsive"><table class="admin-table"><thead><tr><th>Host</th><th>Email</th><th>Joined</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($hosts as $host)<tr><td><strong>{{ $host->name }}</strong></td><td>{{ $host->email }}</td><td>{{ $host->created_at->format('d M Y') }}</td><td class="text-end"><form method="POST" action="{{ route('admin.hosts.remove',$host->id) }}" onsubmit="return confirm('Remove host access from this user?')">@csrf @method('DELETE')<button class="admin-btn admin-btn-danger"><i class="ti ti-user-minus"></i> Remove Host</button></form></td></tr>@empty<tr><td colspan="4"><div class="admin-empty"><i class="ti ti-home-off"></i>No hosts found.</div></td></tr>@endforelse</tbody></table></div>@if($hosts->hasPages())<div class="admin-pagination">{{ $hosts->links() }}</div>@endif</div></div>
</div>
@push('scripts')<script>document.getElementById('hostUser')?.addEventListener('change',function(){document.getElementById('assignHostForm').action='{{ url('/admin/hosts') }}/'+this.value;});</script>@endpush
@endsection
