@extends('layouts.admin')
@section('title', 'Manage Users')
@section('content')
<div class="admin-page-head"><div><h1>Manage Users</h1><p>Create, edit, and remove user accounts.</p></div><span class="admin-badge badge-blue">{{ $users->total() }} users</span></div>
<div class="row g-3">
<div class="col-xl-4"><div class="admin-card"><div class="admin-card-header"><h2>Add User</h2></div><div class="admin-card-body"><form method="POST" action="{{ route('admin.users.store') }}">@csrf<div class="mb-3"><label class="admin-form-label">Name</label><input class="admin-form-control" name="name" required></div><div class="mb-3"><label class="admin-form-label">Email</label><input class="admin-form-control" type="email" name="email" required></div><div class="mb-3"><label class="admin-form-label">Password</label><input class="admin-form-control" type="password" name="password" required></div><div class="mb-3"><label class="admin-form-label">Role</label><select class="admin-form-control" name="role"><option value="user">User</option><option value="host">Host</option></select></div><button class="admin-btn admin-btn-primary w-100" type="submit"><i class="ti ti-user-plus"></i> Create User</button></form></div></div></div>
<div class="col-xl-8"><div class="admin-card"><div class="admin-card-header"><h2>All Users</h2></div><div class="table-responsive"><table class="admin-table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($users as $user)<tr><td><strong>{{ $user->name }}</strong></td><td>{{ $user->email }}</td><td>@foreach($user->roles as $role)<span class="admin-badge {{ strtolower($role->name)==='admin'?'badge-red':(strtolower($role->name)==='host'?'badge-green':'badge-blue') }} me-1">{{ ucfirst($role->name) }}</span>@endforeach</td><td class="text-end"><form action="{{ route('admin.users.destroy',$user->id) }}" method="POST" onsubmit="return confirm('Delete this user? Related data may also be deleted.')">@csrf @method('DELETE')<button class="admin-btn admin-btn-danger" type="submit" @disabled(auth()->id()===$user->id)><i class="ti ti-trash"></i> Delete</button></form></td></tr>@empty<tr><td colspan="4"><div class="admin-empty"><i class="ti ti-users-off"></i>No users found.</div></td></tr>@endforelse</tbody></table></div>@if($users->hasPages())<div class="admin-pagination">{{ $users->links() }}</div>@endif</div></div>
</div>
@endsection
