
<?php $__env->startSection('title', 'Manage Homestays'); ?>
<?php $__env->startSection('content'); ?>
<div class="admin-page-head"><div><h1>Manage Homestays</h1><p>View, edit, and remove homestay listings.</p></div><span class="admin-badge badge-blue"><?php echo e($homestays->total()); ?> listings</span></div>
<div class="admin-card"><div class="admin-card-header"><h2>All Homestays</h2></div><div class="table-responsive"><table class="admin-table"><thead><tr><th>Homestay</th><th>Host</th><th>Province</th><th>Price / night</th><th>Rating</th><th class="text-end">Action</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $homestays; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $hotel): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($hotel->name); ?></strong><div class="admin-muted" style="font-size:12px"><?php echo e($hotel->address ?: 'No address'); ?></div></td><td><?php echo e($hotel->host_name ?: 'Unknown'); ?></td><td><?php echo e($hotel->province_name ?: '—'); ?></td><td>$<?php echo e(number_format($hotel->price_per_night,2)); ?></td><td><?php echo e($hotel->star_rating ? $hotel->star_rating . '/5' : '—'); ?></td><td class="text-end"><div class="d-inline-flex gap-2"><a class="admin-btn admin-btn-light" href="<?php echo e(route('admin.homestays.edit',$hotel->id)); ?>"><i class="ti ti-edit"></i> Edit</a><form action="<?php echo e(route('admin.homestays.destroy',$hotel->id)); ?>" method="POST" onsubmit="return confirm('Delete this homestay? Its reviews and images may also be removed.')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="admin-btn admin-btn-danger" type="submit"><i class="ti ti-trash"></i> Delete</button></form></div></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6"><div class="admin-empty"><i class="ti ti-building-off"></i>No homestays found.</div></td></tr><?php endif; ?>
</tbody></table></div><?php if($homestays->hasPages()): ?><div class="admin-pagination"><?php echo e($homestays->links()); ?></div><?php endif; ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\nana2\OneDrive\Documents\Vs Code\HomeStay_Finder_Role5_modified_source\resources\views/admin/homestays.blade.php ENDPATH**/ ?>