
<?php $__env->startSection('title', 'Manage Users'); ?>
<?php $__env->startSection('content'); ?>
<div class="admin-page-head"><div><h1>Manage Users</h1><p>Create, edit, and remove user accounts.</p></div><span class="admin-badge badge-blue"><?php echo e($users->total()); ?> users</span></div>
<div class="row g-3">
<div class="col-xl-4"><div class="admin-card"><div class="admin-card-header"><h2>Add User</h2></div><div class="admin-card-body"><form method="POST" action="<?php echo e(route('admin.users.store')); ?>"><?php echo csrf_field(); ?><div class="mb-3"><label class="admin-form-label">Name</label><input class="admin-form-control" name="name" required></div><div class="mb-3"><label class="admin-form-label">Email</label><input class="admin-form-control" type="email" name="email" required></div><div class="mb-3"><label class="admin-form-label">Password</label><input class="admin-form-control" type="password" name="password" required></div><div class="mb-3"><label class="admin-form-label">Role</label><select class="admin-form-control" name="role"><option value="user">User</option><option value="host">Host</option></select></div><button class="admin-btn admin-btn-primary w-100" type="submit"><i class="ti ti-user-plus"></i> Create User</button></form></div></div></div>
<div class="col-xl-8"><div class="admin-card"><div class="admin-card-header"><h2>All Users</h2></div><div class="table-responsive"><table class="admin-table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th class="text-end">Action</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($user->name); ?></strong></td><td><?php echo e($user->email); ?></td><td><?php $__currentLoopData = $user->roles; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $role): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><span class="admin-badge <?php echo e(strtolower($role->name)==='admin'?'badge-red':(strtolower($role->name)==='host'?'badge-green':'badge-blue')); ?> me-1"><?php echo e(ucfirst($role->name)); ?></span><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></td><td class="text-end"><form action="<?php echo e(route('admin.users.destroy',$user->id)); ?>" method="POST" onsubmit="return confirm('Delete this user? Related data may also be deleted.')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="admin-btn admin-btn-danger" type="submit" <?php if(auth()->id()===$user->id): echo 'disabled'; endif; ?>><i class="ti ti-trash"></i> Delete</button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="4"><div class="admin-empty"><i class="ti ti-users-off"></i>No users found.</div></td></tr><?php endif; ?></tbody></table></div><?php if($users->hasPages()): ?><div class="admin-pagination"><?php echo e($users->links()); ?></div><?php endif; ?></div></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\nana2\OneDrive\Documents\Vs Code\HomeStay_Finder_Role5_modified_source\resources\views/admin/users.blade.php ENDPATH**/ ?>