
<?php $__env->startSection('title', 'Manage Hosts'); ?>
<?php $__env->startSection('content'); ?>
<div class="admin-page-head"><div><h1>Manage Hosts</h1><p>Assign host access and manage existing hosts.</p></div><span class="admin-badge badge-green"><?php echo e($hosts->total()); ?> hosts</span></div>
<div class="row g-3">
<div class="col-xl-4"><div class="admin-card"><div class="admin-card-header"><h2>Assign Host Role</h2></div><div class="admin-card-body"><form method="POST" action="<?php echo e($users->count() ? route('admin.hosts.assign',$users->first()->id) : '#'); ?>" id="assignHostForm"><?php echo csrf_field(); ?><div class="mb-3"><label class="admin-form-label">Select user</label><select class="admin-form-control" id="hostUser" required><option value="">Choose a user</option><?php $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($user->id); ?>"><?php echo e($user->name); ?> — <?php echo e($user->email); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><button class="admin-btn admin-btn-primary w-100" type="submit" <?php echo e($users->isEmpty() ? 'disabled' : ''); ?>><i class="ti ti-user-plus"></i> Make Host</button></form></div></div></div>
<div class="col-xl-8"><div class="admin-card"><div class="admin-card-header"><h2>Current Hosts</h2></div><div class="table-responsive"><table class="admin-table"><thead><tr><th>Host</th><th>Email</th><th>Joined</th><th class="text-end">Action</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $hosts; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $host): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($host->name); ?></strong></td><td><?php echo e($host->email); ?></td><td><?php echo e($host->created_at->format('d M Y')); ?></td><td class="text-end"><form method="POST" action="<?php echo e(route('admin.hosts.remove',$host->id)); ?>" onsubmit="return confirm('Remove host access from this user?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="admin-btn admin-btn-danger"><i class="ti ti-user-minus"></i> Remove Host</button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="4"><div class="admin-empty"><i class="ti ti-home-off"></i>No hosts found.</div></td></tr><?php endif; ?></tbody></table></div><?php if($hosts->hasPages()): ?><div class="admin-pagination"><?php echo e($hosts->links()); ?></div><?php endif; ?></div></div>
</div>
<?php $__env->startPush('scripts'); ?><script>document.getElementById('hostUser')?.addEventListener('change',function(){document.getElementById('assignHostForm').action='<?php echo e(url('/admin/hosts')); ?>/'+this.value;});</script><?php $__env->stopPush(); ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\nana2\OneDrive\Documents\Vs Code\HomeStay_Finder_Role5_modified_source\resources\views/admin/hosts.blade.php ENDPATH**/ ?>